// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5nZV6HdvfqOFa7sixiIJVAbI-PyIyER8',
    appId: '1:1088613682505:web:e73dc4befc25d13bb2de98',
    messagingSenderId: '1088613682505',
    projectId: 'playtico-0123',
    authDomain: 'playtico-0123.firebaseapp.com',
    storageBucket: 'playtico-0123.appspot.com',
    measurementId: 'G-FMRPJV528H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiwzWlNxeDiItBvMbZshxji94OsvvzGAQ',
    appId: '1:1088613682505:android:9d208a2318f04bb5b2de98',
    messagingSenderId: '1088613682505',
    projectId: 'playtico-0123',
    storageBucket: 'playtico-0123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv9DBOY3VXk0Zx9-yh9Y2mjkLyH5omRBk',
    appId: '1:1088613682505:ios:94a901a9444001f6b2de98',
    messagingSenderId: '1088613682505',
    projectId: 'playtico-0123',
    storageBucket: 'playtico-0123.appspot.com',
    iosClientId: '1088613682505-ln6kc4oa2f9p87sd4aq4ncgsb705ufft.apps.googleusercontent.com',
    iosBundleId: 'com.playtico.playticoapp',
  );
}
